# This is a basic workflow to help you get started with Actions

name: Release

# Controls when the workflow will run
on:
  # Triggers the workflow on push with a tag
  push:
    tags:
      - "v*"
  # nightly
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "0 23 * * *"

  # Triggers on creation of a release
  # release:
  #     types:
  #         - created

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Checkout main
        uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive --remote
      - uses: actions/setup-node@master
        with:
          node-version: 16
      - name: Install dependencies
        run: cd ./chaiNNer && npm ci --force
      - name: Install necessary FlatPak tools
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo apt update && sudo apt install flatpak flatpak-builder elfutils
      - name: Build nightly release
        run: cd ./chaiNNer && npm run make
      - name: Upload to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file_glob: true
          file: ./chaiNNer/out/make/**
          tag: nightly
          overwrite: true
          body: Built on ${{ github.event.repository.updated_at}}
          release_name: chaiNNer Nightly ${{ github.event.repository.updated_at}}
          prerelease: true
