# This is a basic workflow to help you get started with Actions

name: Release

# Controls when the workflow will run
on:
  # Triggers the workflow on push with a tag
  push:
    tags:
      - "v*"
  # nightly
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "0 23 * * *"

  # Triggers on creation of a release
  # release:
  #     types:
  #         - created

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Checkout main
        uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive --remote
      - uses: actions/setup-node@master
        with:
          node-version: 16
      - name: Install dependencies
        run: cd ./chaiNNer && npm ci --force
      - name: Install necessary FlatPak tools
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo apt update && sudo apt install flatpak flatpak-builder elfutils
      - name: Build nightly release
        run: cd ./chaiNNer && npm run make
      #   - name: Delete old release assets
      #     uses: mknejp/delete-release-assets@v1
      #     with:
      #       token: ${{ github.token }}
      #       tag: nightly
      #       assets: "*.*"
      - name: Set file name env vars
        id: step_one
        run: |
          echo "ZIP=$(find ./chaiNNer/out/make/ -iname *.zip)" >> $GITHUB_ENV
          echo "DMG=$(find ./chaiNNer/out/make/ -iname *.dmg)" >> $GITHUB_ENV
          echo "DEB=$(find ./chaiNNer/out/make/ -iname *.deb)" >> $GITHUB_ENV
          echo "RPM=$(find ./chaiNNer/out/make/ -iname *.rpm)" >> $GITHUB_ENV
          echo "EXE=$(find ./chaiNNer/out/make/ -iname *.exe)" >> $GITHUB_ENV
          echo "NUPKG=$(find ./chaiNNer/out/make/ -iname *.nupkg)" >> $GITHUB_ENV
      - name: Rename build assets
        run: |
          mv ${{ env.ZIP }} ./chaiNNer/out/make/chaiNNer-${{ matrix.os }}-${{ github.event.repository.updated_at }}.zip
          mv ${{ env.DMG }} ./chaiNNer/out/make/chaiNNer-${{ matrix.os }}-${{ github.event.repository.updated_at }}.dmg
          mv ${{ env.DEB }} ./chaiNNer/out/make/chaiNNer-${{ matrix.os }}-${{ github.event.repository.updated_at }}.deb
          mv ${{ env.RPM }} ./chaiNNer/out/make/chaiNNer-${{ matrix.os }}-${{ github.event.repository.updated_at }}.rpm
          mv ${{ env.EXE }} ./chaiNNer/out/make/chaiNNer-${{ matrix.os }}-${{ github.event.repository.updated_at }}.exe
          mv ${{ env.NUPKG }} ./chaiNNer/out/make/chaiNNer-${{ matrix.os }}-${{ github.event.repository.updated_at }}.nupkg
      - name: Update release description
        id: update_release
        uses: tubone24/update_release@v1.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          body: Built on ${{ github.event.repository.updated_at}}
      - name: Upload new release assets
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file_glob: true
          file: ./chaiNNer/out/make/**
          tag: nightly
          overwrite: true
          body: Built on ${{ github.event.repository.updated_at }}
          release_name: chaiNNer Nightly ${{ github.event.repository.updated_at }}
          prerelease: true
