# Modified workflow for manual release without secrets
name: Manual Release

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Checkout submodules
        run: git submodule update --init --recursive --remote

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: |
          cd ./chaiNNer
          npm ci --force

      - name: Build project
        run: |
          cd ./chaiNNer
          npm run make

      - name: Set file name environment variables
        id: set_filenames
        shell: bash
        run: |
          echo "ZIP=$(find ./chaiNNer/out/make/ -iname *.zip)" >> $GITHUB_ENV
          echo "DMG=$(find ./chaiNNer/out/make/ -iname *.dmg)" >> $GITHUB_ENV
          echo "DEB=$(find ./chaiNNer/out/make/ -iname *.deb)" >> $GITHUB_ENV
          echo "RPM=$(find ./chaiNNer/out/make/ -iname *.rpm)" >> $GITHUB_ENV
          echo "EXE=$(find ./chaiNNer/out/make/ -iname *.exe)" >> $GITHUB_ENV

      - name: Rename assets for release
        run: |
          if [[ -n "$ZIP" ]]; then mv "$ZIP" ./chaiNNer/out/make/chaiNNer-nightly.zip; fi
          if [[ -n "$DMG" ]]; then mv "$DMG" ./chaiNNer/out/make/chaiNNer-nightly.dmg; fi
          if [[ -n "$DEB" ]]; then mv "$DEB" ./chaiNNer/out/make/chaiNNer-nightly.deb; fi
          if [[ -n "$RPM" ]]; then mv "$RPM" ./chaiNNer/out/make/chaiNNer-nightly.rpm; fi
          if [[ -n "$EXE" ]]; then mv "$EXE" ./chaiNNer/out/make/chaiNNer-nightly.exe; fi

      - name: Create a new release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file_glob: true
          file: ./chaiNNer/out/make/**
          tag: manual-release
          overwrite: true
          release_name: Manual Build Release
          prerelease: true
          body: |
            Build information:
            Built on $(date -u)
